blank_issues_enabled: false
contact_links:
  - name: OpenVidu Discourse forum
    url: https://openvidu.discourse.group/
    about: If your question is about a certain feature or getting support for a specific use case, please use OpenVidu Discourse Group forum
